#' Extract DIMA Database to R Dataframes
#'
#' @description
#' `extract_dima()` queries all rows of all DIMA tables existing at the time
#' this function was created. Because there is no programatic way to retrieve
#' a list of all data table names from DIMA without privileged access, this
#' function cannot recognize if the DIMA schema has changed to add or delete
#' tables.
#'
#' **Note: This function only works on Windows systems, due to unavailability
#' of a MS Access driver on other systems.**
#'
#' @param dima_path A filepath to a DIMA database.
#'
#' @return A list of dataframes, one for each DIMA table and with the same names.
#' @export
extract_dima <- function (dima_path) {
  query <- list(
    "tblApplicationConstants" = "SELECT * FROM tblApplicationConstants",
    "tblBSNE_Box" = "SELECT * FROM tblBSNE_Box",
    "tblBSNE_BoxCollection" = "SELECT * FROM tblBSNE_BoxCollection",
    "tblBSNE_Stack" = "SELECT * FROM tblBSNE_Stack",
    "tblBSNE_TrapCollection" = "SELECT * FROM tblBSNE_TrapCollection",
    "tblCanopyGapHeader" = "SELECT * FROM tblCanopyGapHeader",
    "tblCanopyGapSpecies" = "SELECT * FROM tblCanopyGapSpecies",
    "tblCompactDetail" = "SELECT * FROM tblCompactDetail",
    "tblCompactHeader" = "SELECT * FROM tblCompactHeader",
    "tblCounty" = "SELECT * FROM tblCounty",
    "tblDKDetail" = "SELECT * FROM tblDKDetail",
    "tblDKHeader" = "SELECT * FROM tblDKHeader",
    "tblDryWtCompYield" = "SELECT * FROM tblDryWtCompYield",
    "tblDryWtHeader" = "SELECT * FROM tblDryWtHeader",
    "tblDryWtSpecies" = "SELECT * FROM tblDryWtSpecies",
    "tblEcolSites" = "SELECT * FROM tblEcolSites",
    "tblESDDominantPerennialHeight" = "SELECT * FROM tblESDDominantPerennialHeight",
    "tblESDRockFragments" = "SELECT * FROM tblESDRockFragments",
    "tblESDWaypoints" = "SELECT * FROM tblESDWaypoints",
    "tblGapDetail" = "SELECT * FROM tblGapDetail",
    "tblGapHeader" = "SELECT * FROM tblGapHeader",
    "tblGISDatums" = "SELECT * FROM tblGISDatums",
    "tblInfiltrationDetail" = "SELECT * FROM tblInfiltrationDetail",
    "tblInfiltrationHeader" = "SELECT * FROM tblInfiltrationHeader",
    "tblKMLFields" = "SELECT * FROM tblKMLFields",
    "tblLICDetail" = "SELECT * FROM tblLICDetail",
    "tblLICHeader" = "SELECT * FROM tblLICHeader",
    "tblLICSpecies" = "SELECT * FROM tblLICSpecies",
    "tblLines" = "SELECT * FROM tblLines",
    "tblLowerCanopy" = "SELECT * FROM tblLowerCanopy",
    "tblLPIDetail" = "SELECT * FROM tblLPIDetail",
    "tblLPIHeader" = "SELECT * FROM tblLPIHeader",
    "tblLPILowerCodes" = "SELECT * FROM tblLPILowerCodes",
    "tblLPIMeasures" = "SELECT * FROM tblLPIMeasures",
    "tblLPIMeasures default" = "SELECT * FROM tblLPIMeasures default",
    "tblLPIOtherCodes" = "SELECT * FROM tblLPIOtherCodes",
    "tblLPISpecies" = "SELECT * FROM tblLPISpecies",
    "tblMaintBedrock" = "SELECT * FROM tblMaintBedrock",
    "tblMaintCarbonateStage" = "SELECT * FROM tblMaintCarbonateStage",
    "tblMaintDKClass" = "SELECT * FROM tblMaintDKClass",
    "tblMaintErosionPatternClass" = "SELECT * FROM tblMaintErosionPatternClass",
    "tblMaintESDFragmentTypes" = "SELECT * FROM tblMaintESDFragmentTypes",
    "tblMaintESDRupture" = "SELECT * FROM tblMaintESDRupture",
    "tblMaintGeomorphComp" = "SELECT * FROM tblMaintGeomorphComp",
    "tblMaintHorizons" = "SELECT * FROM tblMaintHorizons",
    "tblMaintLandform" = "SELECT * FROM tblMaintLandform",
    "tblMaintLandform1" = "SELECT * FROM tblMaintLandform1",
    "tblMaintMinerologyClasses" = "SELECT * FROM tblMaintMinerologyClasses",
    "tblMaintNASIS" = "SELECT * FROM tblMaintNASIS",
    "tblMaintNearestPerennial" = "SELECT * FROM tblMaintNearestPerennial",
    "tblMaintParentMaterial" = "SELECT * FROM tblMaintParentMaterial",
    "tblMaintParentMaterial1" = "SELECT * FROM tblMaintParentMaterial1",
    "tblMaintParticleSizes" = "SELECT * FROM tblMaintParticleSizes",
    "tblMaintPlotTags" = "SELECT * FROM tblMaintPlotTags",
    "tblMaintPosition" = "SELECT * FROM tblMaintPosition",
    "tblMaintQualIndicators" = "SELECT * FROM tblMaintQualIndicators",
    "tblMaintQualRatings" = "SELECT * FROM tblMaintQualRatings",
    "tblMaintResourceRetentionClasses" = "SELECT * FROM tblMaintResourceRetentionClasses",
    "tblMaintSlopeShape" = "SELECT * FROM tblMaintSlopeShape",
    "tblMaintSoilRedistributionClass" = "SELECT * FROM tblMaintSoilRedistributionClass",
    "tblMaintSoilStability" = "SELECT * FROM tblMaintSoilStability",
    "tblMaintSoilTempClasses" = "SELECT * FROM tblMaintSoilTempClasses",
    "tblMaintSoilTexture" = "SELECT * FROM tblMaintSoilTexture",
    "tblMaintStructureShapes" = "SELECT * FROM tblMaintStructureShapes",
    "tblMaintSurfaceSoilProperties" = "SELECT * FROM tblMaintSurfaceSoilProperties",
    "tblMethods" = "SELECT * FROM tblMethods",
    "tblNestedFreqDetail" = "SELECT * FROM tblNestedFreqDetail",
    "tblNestedFreqHeader" = "SELECT * FROM tblNestedFreqHeader",
    "tblNestedFreqSpeciesDetail" = "SELECT * FROM tblNestedFreqSpeciesDetail",
    "tblNestedFreqSpeciesSummary" = "SELECT * FROM tblNestedFreqSpeciesSummary",
    "tblNoneSpecies" = "SELECT * FROM tblNoneSpecies",
    "tblOcularCovDetail" = "SELECT * FROM tblOcularCovDetail",
    "tblOcularCovHeader" = "SELECT * FROM tblOcularCovHeader",
    "tblOwnership" = "SELECT * FROM tblOwnership",
    "tblPastCondHeader" = "SELECT * FROM tblPastCondHeader",
    "tblPDFs" = "SELECT * FROM tblPDFs",
    "tblPeople" = "SELECT * FROM tblPeople",
    "tblPhotos" = "SELECT * FROM tblPhotos",
    "tblPlantDenDetail" = "SELECT * FROM tblPlantDenDetail",
    "tblPlantDenHeader" = "SELECT * FROM tblPlantDenHeader",
    "tblPlantDenQuads" = "SELECT * FROM tblPlantDenQuads",
    "tblPlantDenSpecies" = "SELECT * FROM tblPlantDenSpecies",
    "tblPlantLenDetail" = "SELECT * FROM tblPlantLenDetail",
    "tblPlantLenHeader" = "SELECT * FROM tblPlantLenHeader",
    "tblPlantProdDetail" = "SELECT * FROM tblPlantProdDetail",
    "tblPlantProdHeader" = "SELECT * FROM tblPlantProdHeader",
    "tblPlotCustomLookup1" = "SELECT * FROM tblPlotCustomLookup1",
    "tblPlotCustomLookup2" = "SELECT * FROM tblPlotCustomLookup2",
    "tblPlotCustomLookup3" = "SELECT * FROM tblPlotCustomLookup3",
    "tblPlotFormDefaults" = "SELECT * FROM tblPlotFormDefaults",
    "tblPlotHistory" = "SELECT * FROM tblPlotHistory",
    "tblPlotMgtCropData" = "SELECT * FROM tblPlotMgtCropData",
    "tblPlotMgtDetail" = "SELECT * FROM tblPlotMgtDetail",
    "tblPlotMgtHeader" = "SELECT * FROM tblPlotMgtHeader",
    "tblPlotNotes" = "SELECT * FROM tblPlotNotes",
    "tblPlots" = "SELECT * FROM tblPlots",
    "tblPlotSpecies" = "SELECT * FROM tblPlotSpecies",
    "tblPlotTags" = "SELECT * FROM tblPlotTags",
    "tblPlotVisitDateMethods" = "SELECT * FROM tblPlotVisitDateMethods",
    "tblPTFrameDetail" = "SELECT * FROM tblPTFrameDetail",
    "tblPTFrameHeader" = "SELECT * FROM tblPTFrameHeader",
    "tblQualDetail" = "SELECT * FROM tblQualDetail",
    "tblQualHeader" = "SELECT * FROM tblQualHeader",
    "tblReportIndicators" = "SELECT * FROM tblReportIndicators",
    "tblReportParams" = "SELECT * FROM tblReportParams",
    "tblReportParms" = "SELECT * FROM tblReportParms",
    "tblReports" = "SELECT * FROM tblReports",
    "tblRiparProDetail" = "SELECT * FROM tblRiparProDetail",
    "tblRiparProHeader" = "SELECT * FROM tblRiparProHeader",
    "tblRiparSurvDetail" = "SELECT * FROM tblRiparSurvDetail",
    "tblRiparSurvHeader" = "SELECT * FROM tblRiparSurvHeader",
    "tblRiparSurvSpecies" = "SELECT * FROM tblRiparSurvSpecies",
    "tblRptCalcDetails" = "SELECT * FROM tblRptCalcDetails",
    "tblSageEval" = "SELECT * FROM tblSageEval",
    "tblSegeLek" = "SELECT * FROM tblSegeLek",
    "tblSageRange" = "SELECT * FROM tblSageRange",
    "tblSageThresholds" = "SELECT * FROM tblSageThresholds",
    "tblSageThresholds_baseline" = "SELECT * FROM tblSageThresholds_baseline",
    "tblSamplePointRptTemp" = "SELECT * FROM tblSamplePointRptTemp",
    "tblSites" = "SELECT * FROM tblSites",
    "tblSoilPitHorizons" = "SELECT * FROM tblSoilPitHorizons",
    "tblSoilPits" = "SELECT * FROM tblSoilPits",
    "tblSoilStabDetail" = "SELECT * FROM tblSoilStabDetail",
    "tblSoilStabHeader" = "SELECT * FROM tblSoilStabHeader",
    "tblSoilStabSubtotal" = "SELECT * FROM tblSoilStabSubtotal",
    "tblSoilSurface" = "SELECT * FROM tblSoilSurface",
    "tblSoilSurfaceOcular" = "SELECT * FROM tblSoilSurfaceOcular",
    "tblSortSpecies" = "SELECT * FROM tblSortSpecies",
    "tblSpecies" = "SELECT * FROM tblSpecies",
    "tblSpeciesGeneric" = "SELECT * FROM tblSpeciesGeneric",
    "tblSpeciesGeneric_baseline" = "SELECT * FROM tblSpeciesGeneric_baseline",
    "tblSpeciesGeneric_baseline new" = "SELECT * FROM tblSpeciesGeneric_baseline new",
    "tblSpeciesGeneric_baseline old" = "SELECT * FROM tblSpeciesGeneric_baseline old",
    "tblSpeciesGeneric1" = "SELECT * FROM tblSpeciesGeneric1",
    "tblSpeciesGroups" = "SELECT * FROM tblSpeciesGroups",
    "tblSpeciesGrowthHabit" = "SELECT * FROM tblSpeciesGrowthHabit",
    "tblSpecRichAbundance" = "SELECT * FROM tblSpecRichAbundance",
    "tblSpecRichDetail" = "SELECT * FROM tblSpecRichDetail",
    "tblSpecRichHeader" = "SELECT * FROM tblSpecRichHeader",
    "tblStateMLRAs" = "SELECT * FROM tblStateMLRAs",
    "tblStateMLRAs1" = "SELECT * FROM tblStateMLRAs1",
    "tblTempPlots" = "SELECT * FROM tblTempPlots",
    "tblTempSites" = "SELECT * FROM tblTempSites",
    "tblTempSpecies" = "SELECT * FROM tblTempSpecies",
    "tblTreeDenDetail" = "SELECT * FROM tblTreeDenDetail",
    "tblTreeDenHeader" = "SELECT * FROM tblTreeDenHeader",
    "tblUtilDetail" = "SELECT * FROM tblUtilDetail",
    "tblUtilHeader" = "SELECT * FROM tblUtilHeader",
    "tblUtilTransect" = "SELECT * FROM tblUtilTransect",
    "tblVegStructDetail" = "SELECT * FROM tblVegStructDetail",
    "tblVegStructHeader" = "SELECT * FROM tblVegStructHeader",
    "tblUnknownTracking" = "SELECT * FROM tblUnknownTracking"
  )
  return(query_dima(dima_path, query))
}
